### ISSUE TITLE
Error in Example 3.3 

### ISSUE THREAD

**Issue by kingstenbanh** [oreillymedia/knockout_js#1]
I tried to follow the example from the book. However, when I refresh the page I received the following error message.

Uncaught SyntaxError: Unable to process binding "foreach: function (){return { data:books,afterRender:loadImage} }"
Message: Unable to parse bindings.
Bindings value: attr { id: 'image_' + isbn }
Message: Unexpected identifier

I though I make a typo, but the example I ran after copy and paste straight from github doesn't work either. Please help!

Thanks

**Comment by karent** [comment]
Thanks for reporting this error. I've submitted it as errata on the book's catalog page: http://www.oreilly.com/catalog/errataunconfirmed.csp?isbn=0636920035367. This should be addressed in the book's next reprint.
